remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Yojan David Gil Posada
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/axu-aux.appspot.com/o/Imagen%20de%20WhatsApp%202023-09-25%20a%20las%2022.30.19.jpg?alt=media&token=ff915143-cbb9-40cf-983a-93a907640447&_gl=1*1cpjdj5*_ga*Nzg0OTE1OC4xNjk1MDY4MTUy*_ga_CW55HF8NVT*MTY5NjI5MjQ2Mi4zLjEuMTY5NjI5MjQ5NC4yOC4wLjA.
